"""update colmn student_id in AIAgent tabel

Revision ID: 544619c6fad8
Revises: 530af6f5c7cc
Create Date: 2025-02-11 05:48:13.544295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544619c6fad8'
down_revision: Union[str, None] = '530af6f5c7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ai_agents', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_agents', type_='foreignkey')
    op.drop_column('ai_agents', 'student_id')
    # ### end Alembic commands ###
