"""add test_papers and test_papers_record tables

Revision ID: 5bc3509df597
Revises: 7443dcf56a7b
Create Date: 2025-01-04 05:14:53.250627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc3509df597'
down_revision: Union[str, None] = '7443dcf56a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 先创建枚举类型（如果不存在）
    userrole_enum = sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # 使用 USING 子句进行类型转换
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_papers_id'), 'test_papers', ['id'], unique=False)
    op.create_table('test_paper_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_paper_records_id'), 'test_paper_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_test_paper_records_id'), table_name='test_paper_records')
    op.drop_table('test_paper_records')
    op.drop_index(op.f('ix_test_papers_id'), table_name='test_papers')
    op.drop_table('test_papers')
    # ### end Alembic commands ###
