"""add column analysis_type in analysis_results tabel

Revision ID: 5d04a2fa1e6d
Revises: 5bc3509df597
Create Date: 2025-01-05 08:20:34.088170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d04a2fa1e6d'
down_revision: Union[str, None] = '5bc3509df597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('analysis_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'analysis_type')
    # ### end Alembic commands ###
