"""add some column in students and teachers tables

Revision ID: 7443dcf56a7b
Revises: 7ff50fa09861
Create Date: 2024-12-30 08:02:15.432610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7443dcf56a7b'
down_revision: Union[str, None] = '7ff50fa09861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.add_column('teachers', sa.Column('username', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'full_name')
    op.drop_column('teachers', 'username')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
